### ISSUE TITLE
make the folder/icon/text color match the accent in Yellow Accent

### ISSUE THREAD

**Issue by ctf0** [saadq/Materialize-Appbar#5]
the current color is a bit lime-ish

**Comment by saadq** [comment]
This is something that had annoyed me about the yellow accent, I didn't really like the inconsistency between the asset colors and the appbar. It looks like the creator of the original Material Theme has since modified the asset colors to better match the appbar, so I'll be doing the same to these themes asap. Thanks for bringing it to my attention!

**Comment by ctf0** [comment]
sure :)

**Comment by saadq** [comment]
Sorry about the delay on this, I was going to wait on [this](https://github.com/equinusocio/material-theme/commit/0bce81def06c7fc763daf02d1e982928a80030b9) since I found it kind of weird that the "yellow" seems to look like a shade of orange, but it looks like he doesn't really want to change it so I'll probably just go with that orange-ish yellow as well for consistency. Will have this pushed either by tomorrow or the day after.

**Comment by ctf0** [comment]
its all good, thanx 😃
